### ISSUE TITLE
Hello dear it's working in some apps and some apps not

### ISSUE THREAD

**Issue by Mabdelwanis** [bgli100/PermaFlex#1]
For example it's work in settings and AppStore but not work in clock&contacts and many 3rd party apps 
No Hidden Variations button appear in this apps

**Comment by bgli100** [comment]
> For example it's work in settings and AppStore but not work in clock&contacts and many 3rd party apps 
> No Hidden Variations button appear in this apps

Please give bundle identifiers so I could add them?

**Comment by bgli100** [comment]
Fixed in 1.0.4.

**Comment by Mabdelwanis** [comment]
thanks, a lot and seems to be mail fixed too greetings.
